/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.DeptoDAO;
import javax.swing.JOptionPane;
import modelo.Departamento;

/**
 *
 * @author yhonvivas
 */
public class IngresarDepto extends javax.swing.JFrame {

    /**
     * Creates new form IngresarDepto
     */
    public IngresarDepto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTerraza = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtAniosAntD = new javax.swing.JTextField();
        txtIDDepto = new javax.swing.JTextField();
        txtMt2D = new javax.swing.JTextField();
        txtComunaD = new javax.swing.JTextField();
        cbxCantHabitD = new javax.swing.JComboBox<>();
        txtValorRentaD = new javax.swing.JTextField();
        btnVolverD = new javax.swing.JButton();
        btnGuardarD = new javax.swing.JButton();
        btnLimpiarD = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CheckSí = new javax.swing.JCheckBox();
        CheckNo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("ID Departamento:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 130, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 10));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Metros Cuadrados:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, 10));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Comuna:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 60, 20));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Cant. Habitaciones:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Valor Renta:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Años Antiguedad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 20));

        txtAniosAntD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAniosAntDActionPerformed(evt);
            }
        });
        jPanel1.add(txtAniosAntD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 110, -1));

        txtIDDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDDeptoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 110, -1));
        jPanel1.add(txtMt2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 110, -1));
        jPanel1.add(txtComunaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 110, -1));

        cbxCantHabitD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opción", "1", "2", "3", "4", "5", "6" }));
        jPanel1.add(cbxCantHabitD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 150, -1));
        jPanel1.add(txtValorRentaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, -1));

        btnVolverD.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnVolverD.setForeground(new java.awt.Color(51, 51, 51));
        btnVolverD.setText("Volver");
        btnVolverD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverD, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        btnGuardarD.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnGuardarD.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarD.setText("Guardar");
        btnGuardarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        btnLimpiarD.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnLimpiarD.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpiarD.setText("Limpiar");
        btnLimpiarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 120, 90));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/favicon.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 60, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/depto.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 260, 370));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Terraza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        CheckSí.setBackground(new java.awt.Color(255, 255, 255));
        btgTerraza.add(CheckSí);
        CheckSí.setText("Sí");

        CheckNo.setBackground(new java.awt.Color(255, 255, 255));
        btgTerraza.add(CheckNo);
        CheckNo.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckSí)
                .addGap(31, 31, 31)
                .addComponent(CheckNo)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckSí)
                    .addComponent(CheckNo))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDDeptoActionPerformed

    private void btnVolverDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverDActionPerformed

    private void btnGuardarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDActionPerformed
        String id_vivienda,comuna,terraza;
        double mt2d;
        int cantHabitD,valorRentaD,anio_antig,cant_piso;

        if(btgTerraza.getSelection() == null ){
            JOptionPane.showMessageDialog(this, "Debe seleccinar si tiene terraza o no");
            return;
        }

        if(cbxCantHabitD.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Debe seleccionar la cantidad de habitaciones");
            return;
        }

        id_vivienda = txtIDDepto.getText();
        mt2d = Double.parseDouble(txtMt2D.getText());
        comuna = txtComunaD.getText();
        cantHabitD = Integer.parseInt(cbxCantHabitD.getSelectedItem().toString());
        valorRentaD = Integer.parseInt(txtValorRentaD.getText());
        anio_antig = Integer.parseInt(txtAniosAntD.getText());
        terraza = terraza();

        Departamento dep = new Departamento(id_vivienda, mt2d, comuna, cantHabitD, valorRentaD, anio_antig, terraza);
        DeptoDAO depDAO = new DeptoDAO();

        if(depDAO.buscarDepto(id_vivienda) == null){
            depDAO.ingresarDepto(dep);
            JOptionPane.showMessageDialog(this, "Departamento ingresado con exito");
        }else{
            JOptionPane.showMessageDialog(this, "Departamento ya existe");
        }
    }//GEN-LAST:event_btnGuardarDActionPerformed
    
    public String terraza(){
        if(CheckSí.isSelected())
            return "Sí";
        if(CheckNo.isSelected())
            return "No";
        return null;
    }
    
    private void btnLimpiarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDActionPerformed
        txtIDDepto.setText(null);
        txtMt2D.setText(null);
        txtComunaD.setText(null);
        cbxCantHabitD.setSelectedIndex(-1);
        txtValorRentaD.setText(null);
        txtAniosAntD.setText(null);
        btgTerraza.clearSelection();
        txtIDDepto.requestFocus();
    }//GEN-LAST:event_btnLimpiarDActionPerformed

    private void txtAniosAntDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAniosAntDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAniosAntDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckNo;
    private javax.swing.JCheckBox CheckSí;
    private javax.swing.ButtonGroup btgTerraza;
    private javax.swing.JButton btnGuardarD;
    private javax.swing.JButton btnLimpiarD;
    private javax.swing.JButton btnVolverD;
    private javax.swing.JComboBox<String> cbxCantHabitD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtAniosAntD;
    private javax.swing.JTextField txtComunaD;
    private javax.swing.JTextField txtIDDepto;
    private javax.swing.JTextField txtMt2D;
    private javax.swing.JTextField txtValorRentaD;
    // End of variables declaration//GEN-END:variables
}
